language: node_js
node_js:
  - "node"
after_success: npm run coverage
notifications:
  email:
  on_success: never
  on_failure: never


language: node_js
node_js:
  - "node"

install:
  - npm install
  - npm install -g codecov

script:
  - npm test

services:
  - postgresql

env:
  - TEST_DB_URL=postgres://admin:password@localhost:5432/factracktest

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE factracktest;' -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD '1234';" -U postgres
  - psql -c "ALTER DATABASE factracktest OWNER TO admin;" -U postgres